apiVersion: v1
kind: Service
metadata:
  name: mdb-instance-0
  namespace: default
  labels:
    name: mdb-instance-0
spec:
  selector:
    app: mdb-instance-0-ss
  ports:
  - port: "<mongodb-backend-port from ConfigMap>"
    targetPort: "<mongodb-backend-port from ConfigMap>"
    name: mdb-port
    protocol: TCP
  type: ClusterIP
  clusterIP: None
