apiVersion: v1
kind: Service
metadata:
  name: bdb-instance-0
  namespace: default
  labels:
    name: bdb-instance-0
spec:
  selector:
    app: bdb-instance-0-dep
  ports:
  - port: "<bigchaindb-api-port from ConfigMap>"
    targetPort: "<bigchaindb-api-port from ConfigMap>"
    name: bdb-port
  - port: "<bigchaindb-ws-port from ConfigMap>"
    targetPort: "<bigchaindb-ws-port from ConfigMap>"
    name: bdb-ws-port
  type: ClusterIP
  clusterIP: None
